import { Platform, StyleSheet } from "react-native";

export const SOS_COLORS = {
  rescueRed: "#C9282D",
  rescueRedDark: "#9F1F23",
  nightBlue: "#102A43",
  paper: "#F7F9FC",
  surface: "#FFFFFF",
  warning: "#B96B00",
  warningSurface: "#FFF4DE",
  ackGreen: "#167A5B",
  ackSurface: "#E6F5EF",
  line: "#CCD6E0",
  muted: "#52677A",
} as const;

export const sosStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: SOS_COLORS.paper },
  scroll: { padding: 20, paddingBottom: 36, gap: 18 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  eyebrow: {
    color: SOS_COLORS.rescueRed,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  title: {
    color: SOS_COLORS.nightBlue,
    fontSize: 32,
    lineHeight: 36,
    fontWeight: "900",
    letterSpacing: -0.8,
  },
  networkBadge: {
    minHeight: 36,
    borderRadius: 18,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  onlineBadge: { borderColor: SOS_COLORS.ackGreen },
  offlineBadge: { borderColor: SOS_COLORS.warning },
  networkText: { fontSize: 12, fontWeight: "800", color: SOS_COLORS.nightBlue },
  panel: {
    backgroundColor: SOS_COLORS.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: SOS_COLORS.line,
    padding: 16,
    gap: 12,
  },
  sectionLabel: {
    color: SOS_COLORS.nightBlue,
    fontSize: 14,
    fontWeight: "800",
  },
  locationValue: {
    color: SOS_COLORS.nightBlue,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace" }),
  },
  body: { color: SOS_COLORS.muted, fontSize: 15, lineHeight: 22 },
  warningText: {
    color: SOS_COLORS.warning,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  linkButton: {
    minHeight: 48,
    justifyContent: "center",
    alignSelf: "flex-start",
  },
  linkButtonText: {
    color: SOS_COLORS.rescueRedDark,
    fontSize: 15,
    fontWeight: "800",
  },
  typeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  typeButton: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: SOS_COLORS.line,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  typeButtonSelected: {
    borderColor: SOS_COLORS.nightBlue,
    backgroundColor: "#EAF0F6",
  },
  typeText: { color: SOS_COLORS.nightBlue, fontSize: 14, fontWeight: "700" },
  input: {
    minHeight: 92,
    borderWidth: 1,
    borderColor: SOS_COLORS.line,
    borderRadius: 12,
    padding: 12,
    color: SOS_COLORS.nightBlue,
    fontSize: 16,
    textAlignVertical: "top",
  },
  primaryButton: {
    minHeight: 58,
    borderRadius: 14,
    backgroundColor: SOS_COLORS.rescueRed,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
  },
  primaryButtonDisabled: { opacity: 0.48 },
  primaryButtonText: {
    color: SOS_COLORS.surface,
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  confirmPanel: {
    borderColor: SOS_COLORS.rescueRed,
    backgroundColor: "#FFF7F7",
  },
  confirmTitle: {
    color: SOS_COLORS.nightBlue,
    fontSize: 18,
    fontWeight: "900",
  },
  receipt: { gap: 10 },
  receiptRail: { flexDirection: "row", gap: 6 },
  receiptStep: {
    flex: 1,
    height: 5,
    borderRadius: 3,
    backgroundColor: SOS_COLORS.line,
  },
  receiptStepActive: { backgroundColor: SOS_COLORS.nightBlue },
  receiptStepAck: { backgroundColor: SOS_COLORS.ackGreen },
  receiptStepFailed: { backgroundColor: SOS_COLORS.warning },
  deliveryText: {
    color: SOS_COLORS.nightBlue,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "800",
  },
  codeBox: {
    backgroundColor: SOS_COLORS.ackSurface,
    borderRadius: 12,
    padding: 14,
    gap: 4,
  },
  code: {
    color: SOS_COLORS.ackGreen,
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 2,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace" }),
  },
  safety: { borderLeftWidth: 4, borderLeftColor: SOS_COLORS.nightBlue },
  callGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  callButton: {
    minWidth: 68,
    minHeight: 52,
    borderWidth: 1,
    borderColor: SOS_COLORS.rescueRed,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  callNumber: {
    color: SOS_COLORS.rescueRedDark,
    fontSize: 18,
    fontWeight: "900",
  },
});
